# Generated by Django 4.2.7 on 2023-11-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftbooker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('m', 'Maintenance'), ('s', 'Shop'), ('c', 'Cleaning'), ('o', 'A/V Operations'), ('p', 'Event Planning')], max_length=1),
        ),
    ]
