# Generated by Django 4.2.7 on 2023-11-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftbooker', '0002_alter_shift_shift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='shiftbooker/static/img'),
        ),
    ]
