# Generated by Django 4.2.7 on 2023-11-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiftbooker', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
