# Generated by Django 4.2.7 on 2023-11-22 12:03

from django.db import migrations, models
import shiftbooker.models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftbooker', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', shiftbooker.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
