# Generated by Django 4.2.7 on 2023-11-17 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiftbooker', '0007_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shiftbooker.volunteer'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='shifts_taken',
            field=models.IntegerField(default=0, verbose_name='Number of shifts taken'),
        ),
    ]
